export const CancelLuisName = 'Utilities.Cancel'
export const ConfirmLuisName = 'Utilities.Confirm'
export const GreetingLuisName = 'Utilities.Greeting'
export const HelpLuisName = 'Utilities.Help'
export const IgnoreUserLuisName = 'IgnoreUser'
export const ShowNextLuisName = 'Utilities.ShowNext'
export const ShowPreviousLuisName = 'Utilities.ShowPrevious'
export const NoneLuisName = 'None'
export const ReminderCreateLuisName = 'Reminder.Create'
export const ShowSettingsLuisName = 'Bot.ShowSettings'
export const StopLuisName = 'Utilities.Stop'
export const UnignoreUserLuisName = 'UnignoreUser'

export const DefaultDialogName = '/'
export const intentThreshold = 0.4
